### ISSUE TITLE
share AC

### ISSUE THREAD

**Issue by xadros1** [codyc1515/homebridge-panasonic-air-conditioner#25]
Hi, how can I please share AC with another account? Spend an hour on that but not able to find anything.

**Comment by EvertJob** [comment]
Login to the app. Than select the airco on the frontpage. Then click on the hamburger menu on the top right and select ‘Userlist’ onder “Owner”.

For every device you want to use you have to create a new user.

**Comment by xadros1** [comment]
There is nothing and no button which I can use for adding.. Do I need to create another account and then add the AC manually?
![D6D40DD3-D238-487F-AEA3-6D78FC3D39AB](https://user-images.githubusercontent.com/64637821/81481554-5d06c900-9231-11ea-826d-b505459ee77f.png)

**Comment by EvertJob** [comment]
What do you see when you open the menu in the upper right?

**Comment by xadros1** [comment]
That is the screenshot I attached. Sorry for different language, but basically there is no button I can use to add another user

**Comment by EvertJob** [comment]
Strange. Normally you have to create a new user and invite him in you’re main account to access the airco. Don’t know the location on Android

**Comment by xadros1** [comment]
Yes, I would expect it like that. Maybe it is not set as main account? How can I check? It is iOS.

**Comment by codyc1515** [comment]
The app is an appallingly bad effort by Panasonic. It doesn't show my indoor temperature at all (how does it know when it's hit the temperature to turn off?) and only shows the outdoors temperature when it's turned on.

All of this is quite annoying. Unfortunately, this also means you need a separate user account because apparently only one person can be logged into the app per account... because security or something I guess.

Anyway, I'm trying to remember back. I think you have to create a new account then go through the setup process again but it asks if it's been set-up before - say yes - then you have to sign back into the original account and approve the access request. It's a real pain!

**Comment by xadros1** [comment]
Yes, I did not tried it that way. I will check, thank you.
