### ISSUE TITLE
Dry setting and I auto X

### ISSUE THREAD

**Issue by putthegundownkinkade** [codyc1515/homebridge-panasonic-air-conditioner#64]
Hi. This is  a brilliant plug-in. 

Is there any chance you could add a dry setting along with heat, cool and auto?

I also have an I auto x setting but as this is proprietary to panasonic I imagine it can be added to the settings wheel?

thanks!

will

**Comment by codyc1515** [comment]
Unfortunately HomeKit does not support any mode other than Auto, Heat, Cool or Off. The list on the HeaterCooler service cannot be modified either, so we cannot add iAUTO-X. Plausibly we could add it with a switch but it’s not ideal. We previously added a Dehumidifier & Fan service, however this caused the plug-in to behaviour in weird ways with the Home app. This is because the Home app sends the current state of the HeaterCooler service as per the Home app over the top of the current state - very odd behaviour. This causes the HeaterCooler to switch on or off randomly. Any thoughts on this welcomed.

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
