### ISSUE TITLE
New version of app

### ISSUE THREAD

**Issue by svendeneve** [codyc1515/homebridge-panasonic-air-conditioner#82]
Hi, 

Seems that there is again a new version of the app, so the plugin stopped working. Would it be possible to update the code? 
Might it be an option to put the version in the parameters? So it can be changed by the user? 

16-2-2022 20:33:34Panasonic Air Conditioner BridgeBedroom ACWarning - 401 Unauthorized. Login token has expired. 4106 New version app has been published null

Thanks!
Sven

**Comment by 1homebridge** [comment]
I am also having the same issue. Has yours been resolved?

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
