### ISSUE TITLE
Swing Mode

### ISSUE THREAD

**Issue by mkz212** [codyc1515/homebridge-panasonic-air-conditioner#83]
Hi. I have Panasonic Etherea. For me this code works much better:

// Heater Cooler - Swing Mode:

`
if(body.parameters.fanAutoMode == 0 || body.parameters.fanAutoMode == 2 || body.parameters.fanAutoMode == 3) {this.HeaterCooler.getCharacteristic(Characteristic.SwingMode).updateValue(Characteristic.SwingMode.SWING_ENABLED);}
else {this.HeaterCooler.getCharacteristic(Characteristic.SwingMode).updateValue(Characteristic.SwingMode.SWING_DISABLED);}`

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
