### ISSUE TITLE
New plugin implementation

### ISSUE THREAD

**Issue by bimusiek** [codyc1515/homebridge-panasonic-air-conditioner#84]
Hey, I have started working on a plugin for Panasonic AQUAREA systems. 
You can check it here: 
https://github.com/bimusiek/homebridge-panasonic-heat-pump

It supports new API, the docs still needs to be cleaned up but at least it works.
The plugin supports for now Heat Pump from Panasonic, as this is something I have but it won't take long to adjust it to work with Air Cons as well.

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
