### ISSUE TITLE
New Version of the App

### ISSUE THREAD

**Issue by 1homebridge** [codyc1515/homebridge-panasonic-air-conditioner#85]
The plugin is not working. Getting message that temperatures exceed the thresholds and that a new version of the app exists

**Comment by codyc1515** [comment]
This plug-in is now archived and it is advised to use the [homebridge-panasonic-ac-platform](https://github.com/embee8/homebridge-panasonic-ac-platform) plug-in instead. It is based on this plug-in. This plug-in provides support for the devices as a platform (instead of just individual accessories).
